python demo_test.py \
--name syco \
--checkpoints_dir checkpoints \
--model laBaseLUTs \
--netEr Syco \
--epoch pretrained \
--data_mode single \
--gpu_ids 0 \
--is_train 0 \
--real examples/real_images/f436_1_1.jpg \
--mask examples/masks/f436_1_1.png \
--results_dir results_single \
--augment_num 10 \
--keep_res \
--eval \
